import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import MainNavigation from '../components/MainNavigation/MainNavigation';
import Footer from '../components/Footer/Footer';
import { getGlobalData } from '../../data/strapi/getGlobalData';
import { flattenAttributes } from '@/utils/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'JAGAesthetic',
  description: 'Generated by JAGAesthetic',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalData('global-settings');
  const data = flattenAttributes(globalData);

  const allGlobalData = data.data[0];

  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavigation />
        <div className="px-6 lg:px-0">{children}</div>
        <Footer
          copyright={
            allGlobalData.FooterCopyright[0].children?.[0].text
          }
          email={allGlobalData.Email}
          socials={allGlobalData.Socials}
          contactSlogan={allGlobalData.ContactSlogan}
          contactCTA={allGlobalData.ContactCTA}
        />
      </body>
    </html>
  );
}
